### ISSUE TITLE
OSC issue

### ISSUE THREAD

**Issue by dewiweb** [LucienLefebvre/LuPlayer#1]
Hello, 
I tried to control luplayer with OSC addresses specified in documentation without success.
(I tested it with bitfocus companion and I'm sure about ingoing and outgoing ports and ip address of destination)
Could you please be more explicit about osc addresses usable and type of arguments used (float, integer, string, booleean, or without argument) in the documentation?
When it's wrote : "8fadersgainX" , I suppose you want to tell "/8fadersgainX" ? Am I Right?
Maybe OSC is not yet implemented?
Is there a way to debug it to be sure luplayer receive osc messages?

**Comment by LucienLefebvre** [comment]
Hello,

Sorry about the bad documentation on OSC, i will update it.

-Be sure that "Enable OSC" is checked in the settings menu.
-In "Eight faders" mode, to send a gain command for the first player, send a float between 0.0 and 1.0 at the adress :
/8fadersgain1
This will map the float value to a value between -100dB and the value set in "fader maximum value" in the general settings page.
-Unfortunately there is no in-app way to see if Luplayer receive the OSC messages.

Let me know if this helped you,
Lucien

**Comment by dewiweb** [comment]
Thanks! Your reply help me , but  in my opinion  it's  not really intuitive using a float argument to launch a player (with "/8faderspushX" address) . It's just my opinion...
I've tested boolean arguments(True/False), then  integers(0/1) and succeed finally with  floats (0.0/1.0). 
It could be very useful to specify in documentation  kind of argument to be used for each type of  address.
Regards

**Comment by LucienLefebvre** [comment]
> in my opinion it's not really intuitive using a float argument to launch a player (with "/8faderspushX" address) . It's just my opinion...

Yes, I agree with you !
I am using float argument even for boolean-type commands beacause I developped this app alongside touchOsc MK1, the pushbuttons send float message.
I will maybe in the future add support for bool OSC messages, and I have updated the documentation :)

Lucien
